# Generated by Django 3.2.20 on 2023-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbountUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile-pic')),
                ('fullName', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=5)),
                ('designation', models.CharField(max_length=120)),
                ('aboutMe', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
