# Generated by Django 3.2.20 on 2023-08-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abountus',
            old_name='fullName',
            new_name='name',
        ),
    ]
