# Generated by Django 3.2.20 on 2023-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_rename_fullname_abountus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSumarry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happyClient', models.IntegerField()),
                ('complateProjects', models.IntegerField()),
                ('HourseOfSupport', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=160)),
                ('skillParsent', models.IntegerField()),
            ],
        ),
    ]
