# Generated by Django 3.2.20 on 2023-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_servicesumarry_skilllevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientPic', models.ImageField(upload_to='client_profile')),
                ('clientName', models.CharField(max_length=160)),
                ('clientDesignation', models.CharField(max_length=160)),
                ('testMonials', models.TextField()),
            ],
        ),
    ]
