# Generated by Django 4.2.4 on 2023-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_testmonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteName', models.CharField(max_length=260)),
                ('duration', models.CharField(max_length=160)),
                ('aboutEducation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=500)),
                ('aboutProject', models.TextField()),
                ('usesTecknology', models.CharField(max_length=500)),
                ('sourceCode', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=260)),
                ('companyName', models.CharField(max_length=260)),
                ('joinDate', models.DateField()),
                ('regineDate', models.DateField(blank=True, null=True)),
                ('aboutExperience', models.TextField()),
            ],
        ),
    ]
