# Generated by Django 3.2.20 on 2023-08-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
