# Generated by Django 3.2.20 on 2023-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=160)),
            ],
        ),
    ]
