# Generated by Django 3.2.20 on 2023-08-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0010_portfoliocategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=260)),
                ('projectImage', models.ImageField(upload_to='portfolio-pic')),
                ('projectType', models.CharField(max_length=160)),
                ('projectSourceCodeLink', models.CharField(blank=True, max_length=260, null=True)),
                ('projectLiveLink', models.CharField(max_length=260)),
                ('profolioCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.portfoliocategory')),
            ],
        ),
    ]
