# Generated by Django 3.2.20 on 2023-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='projectLiveLink',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
