# Generated by Django 4.2.7 on 2023-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0012_alter_portfolio_projectlivelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='projectDetails',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projectFeature1',
            field=models.CharField(default=1, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projectFeature2',
            field=models.CharField(default=1, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projectFeature3',
            field=models.CharField(default=1, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projectFeature4',
            field=models.CharField(default=1, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='usedTecnology',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
